function [region_table] = create_region_table(all_roi,region_count_WM)

region_table = table(all_roi, region_count_WM(:,1),  region_count_WM(:,2),  region_count_WM(:,3),...
                 region_count_WM(:,4),   region_count_WM(:,5),  region_count_WM(:,6),  region_count_WM(:,7),...
                 region_count_WM(:,8),   region_count_WM(:,9),  region_count_WM(:,10), region_count_WM(:,11),...
                 region_count_WM(:,12),  region_count_WM(:,13), region_count_WM(:,14), region_count_WM(:,15),...
                 region_count_WM(:,16),  region_count_WM(:,17), region_count_WM(:,18), region_count_WM(:,19),...
                 region_count_WM(:,20),  region_count_WM(:,21), region_count_WM(:,22), region_count_WM(:,23),...
                 region_count_WM(:,24),  region_count_WM(:,25), region_count_WM(:,26), region_count_WM(:,27)); 

end